### ISSUE TITLE
Selenium tests flaky on Appveyor

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#201]
I have seen the following error a lot of times when Appveyor runs on my PRs. Running the Appveyor tests again (after a few tries) usually solves the problem. It is not always the same template test. Sometimes multiple tests fail.

```
[xUnit.net 00:10:53.1887760]     Templates.Test.SpaTemplateTest.VueTemplateTest.VueTemplate_Works_NetCore [FAIL]
[xUnit.net 00:10:53.1889853]       OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:2261/session timed out after 10 seconds.
[xUnit.net 00:10:53.1891347]       ---- System.Net.WebException : The operation has timed out.
[xUnit.net 00:10:53.1892143]       Stack Trace:
[xUnit.net 00:10:53.1893254]            at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
[xUnit.net 00:10:53.1894061]            at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
[xUnit.net 00:10:53.1894758]            at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
[xUnit.net 00:10:53.1895488]            at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
[xUnit.net 00:10:53.1896192]            at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
[xUnit.net 00:10:53.1897053]            at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
[xUnit.net 00:10:53.1898021]         C:\projects\templating\test\Templates.Test\Helpers\WebDriverFactory.cs(42,0): at Templates.Test.Helpers.WebDriverFactory.CreateFirefoxDriver()
[xUnit.net 00:10:53.1899973]         C:\projects\templating\test\Templates.Test\Helpers\WebDriverFactory.cs(31,0): at Templates.Test.Helpers.WebDriverFactory.CreateWebDriver()
[xUnit.net 00:10:53.1902018]         C:\projects\templating\test\Templates.Test\Helpers\AspNetProcess.cs(129,0): at Templates.Test.Helpers.AspNetProcess.VisitInBrowser()
[xUnit.net 00:10:53.1904315]         C:\projects\templating\test\Templates.Test\SpaTemplateTest\SpaTemplateTestBase.cs(50,0): at Templates.Test.SpaTemplateTest.SpaTemplateTestBase.TestApplication(String targetFrameworkOverride, Boolean publish)
[xUnit.net 00:10:53.1906694]         C:\projects\templating\test\Templates.Test\SpaTemplateTest\SpaTemplateTestBase.cs(43,0): at Templates.Test.SpaTemplateTest.SpaTemplateTestBase.SpaTemplateImpl(String targetFrameworkOverride, String template)
[xUnit.net 00:10:53.1908639]         ----- Inner Stack Trace -----
[xUnit.net 00:10:53.1909517]            at System.Net.HttpWebRequest.GetResponse()
[xUnit.net 00:10:53.1910531]            at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
```

cc @javiercn @SteveSandersonMS Any ideas?

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Closing this one, as this will be covered by: https://github.com/aspnet/templating/issues/277
