### ISSUE TITLE
Mac tests on Travis fail with PlatformNotSupportedException for libcurl and SSL

### ISSUE THREAD

**Issue by jbagga** [aspnet/Templating#243]
Mac fails because of a known error https://github.com/dotnet/corefx/issues/9728 with the following:
```
[xUnit.net 00:02:21.6105210]     Templates.Test.MvcTemplateTest.MvcTemplate_NoAuth_Works_NetCore(languageOverride: null) [FAIL]
[xUnit.net 00:02:21.6107660]       System.AggregateException : One or more errors occurred. (The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("SecureTransport").)
[xUnit.net 00:02:21.6110290]       ---- System.PlatformNotSupportedException : The handler does not support custom handling of certificates with this combination of libcurl (7.54.0) and its SSL backend ("SecureTransport").
[xUnit.net 00:02:21.6113020]       Stack Trace:
[xUnit.net 00:02:21.6114450]            at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[xUnit.net 00:02:21.6115740]         /_/test/Templates.Test/Helpers/AspNetProcess.cs(123,0): at Templates.Test.Helpers.AspNetProcess.AssertStatusCode(String requestUrl, HttpStatusCode statusCode, String acceptContentType)
[xUnit.net 00:02:21.6118610]         /_/test/Templates.Test/MvcTemplateTest.cs(52,0): at Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthImpl(String targetFrameworkOverride, String languageOverride)
[xUnit.net 00:02:21.6121030]         ----- Inner Stack Trace -----
[xUnit.net 00:02:21.6123760]            at System.Net.Http.CurlHandler.SslProvider.SetSslOptions(EasyRequest easy, ClientCertificateOption clientCertOption)
[xUnit.net 00:02:21.6125770]            at System.Net.Http.CurlHandler.EasyRequest.InitializeCurl()
[xUnit.net 00:02:21.6127450]            at System.Net.Http.CurlHandler.MultiAgent.ActivateNewRequest(EasyRequest easy)
[xUnit.net 00:02:21.6128400]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:02:21.6129390]            at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__62.MoveNext()
```

Requires investigation as .NET Core 2.x should not need OpenSSL for MacOS https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites?tabs=netcore2x#visual-studio-for-mac

https://spin.atomicobject.com/2017/09/28/net-core-osx-libcurl-openssl/

See https://github.com/aspnet/templating/pull/240#issuecomment-358824742

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
Moreover, neither Mac nor Linux tests have passed in at least 2 months for templating. Not sure if retention just doesn't go back that far or if they're literally never passed for this repo.

**Comment by ryanbrandenburg** [comment]
To be clear, by the above I mean on Travis, not that they've also failed on AspNetCI.

**Comment by jbagga** [comment]
I have seen this error frequently for Travis Linux runs:
```
The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at Templates.Test.Helpers.ProcessEx.OnOutputData(Object sender, DataReceivedEventArgs e) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 124
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__17_0(Object edi)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

ITestOutputHelper on Linux seems to be causing an issue.

**Comment by Eilon** [comment]
Moving to RC1. We'll hopefully just switch to dotnet test anyway and we should be able to close this.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, what is the status of this?

**Comment by ryanbrandenburg** [comment]
We no longer run Travis builds for Templating, so there's nothing to do here.
