### ISSUE TITLE
Tests fail due to missing npm package @angular-devkit/core

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#261]
Tests on the release/2.1 branch fail with this error:

https://travis-ci.org/aspnet/templating/jobs/333393331#L1873
```
Error: Cannot find module '@angular-devkit/core'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/home/travis/build/aspnet/templating/test/Templates.Test/bin/Release/netcoreapp2.1/TestTemplates/AspNet.Template.377a14f8809548e69d38ca0d9cf2650f/ClientApp/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
```

cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
It's this issue: https://github.com/angular/angular-cli/issues/9307, which it looks like will be resolved when we update to a slightly newer version of Angular CLI.

**Comment by natemcmaster** [comment]
Ok, I'll try upgrading our CI to node 8

**Comment by natemcmaster** [comment]
Ok, that appeared to fix it. Closing as I added a check that asserts Node is >= 8.0. https://github.com/aspnet/templating/commit/354905dc0060850f7a2dc57442b69918e6eed4cd
