### ISSUE TITLE
Broken tests: MvcTemplate_IndividualAuth_Works_NetCore et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/templating#502]
These tests [fail](http://aspnetci/viewLog.html?buildId=457151&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest) on Win2012 with the following error:

```
System.Exception : Process exited with code 1
StdErr: No executable found matching command "dotnet-C:\b\w\33bdfc1cae7b2a38\packages\dotnet-ef/2.2.0-preview1-34065/tools/netcoreapp2.0/any/dotnet-ef.dll"

StdOut: 
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 142
   at Templates.Test.TemplateTestBase.RunDotNetEfCreateMigration(String migrationName) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 140
   at Templates.Test.MvcTemplateTest.MvcTemplate_IndividualAuthImpl(String targetFrameworkOverride, Boolean useLocalDB, Boolean noHttps) in /_/test/Templates.Test/MvcTemplateTest.cs:line 124
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new mvc -au Individual [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381]
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381\AspNet.Template.609e26211c584274856d2b94e566e381.csproj...
  Restoring packages for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381\AspNet.Template.609e26211c584274856d2b94e566e381.csproj...
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381\obj\AspNet.Template.609e26211c584274856d2b94e566e381.csproj.nuget.g.props.
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381\obj\AspNet.Template.609e26211c584274856d2b94e566e381.csproj.nuget.g.targets.
  Restore completed in 1.19 sec for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381\AspNet.Template.609e26211c584274856d2b94e566e381.csproj.

Restore succeeded.

==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe "C:\b\w\33bdfc1cae7b2a38\packages\dotnet-ef/2.2.0-preview1-34065/tools/netcoreapp2.0/any/dotnet-ef.dll" migrations add mvc [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.1\TestTemplates\AspNet.Template.609e26211c584274856d2b94e566e381]
[ERROR] No executable found matching command "dotnet-C:\b\w\33bdfc1cae7b2a38\packages\dotnet-ef/2.2.0-preview1-34065/tools/netcoreapp2.0/any/dotnet-ef.dll"
```

CC @jbagga

**Comment by ryanbrandenburg** [comment]
An example failure [here](http://aspnetci/viewLog.html?buildId=457151&buildTypeId=Lite_UniverseTest).
