### ISSUE TITLE
Tests logging fails with There is no currently active test.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#514]
E.g. https://travis-ci.org/aspnet/templating/jobs/376048486

```
 The active test run was aborted. Reason: Unhandled Exception: System.InvalidOperationException: There is no currently active test.
     at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
     at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
     at Templates.Test.Helpers.ProcessEx.OnOutputData(Object sender, DataReceivedEventArgs e) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 124
     at System.Diagnostics.Process.OutputReadNotifyUser(String data)
     at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
  --- End of stack trace from previous location where exception was thrown ---
```

**Comment by mkArtakMSFT** [comment]
@pranavkm, is this a consistent failure or random?

**Comment by pranavkm** [comment]
Seems like an ongoing issue. For instance, here's one of the more recent PRs that failed with this - https://travis-ci.org/aspnet/templating/jobs/379549395
