### ISSUE TITLE
Angular5 template lazy SSR an error "ReferenceError: XMLHttpRequest is not defined"

### ISSUE THREAD

**Issue by vasyliv** [aspnet/templating#599]
Hello! Thanks for your templates, there is an error in Angular5 template with SSR (SSR guide from https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)

see the code at here https://github.com/vasyliv/angular5/tree/http

steps to reproduce the error:

- build the project
- run it
- navigate to the page "counter"
- click to reload the page
- see the error in Debug console

```
angular5> fail: Microsoft.AspNetCore.NodeServices[0]
angular5>       ERROR { Error: Uncaught (in promise): ReferenceError: XMLHttpRequest is not defined
angular5>       ReferenceError: XMLHttpRequest is not defined
angular5>           at BrowserXhr.build (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2125:19)
angular5>           at Observable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2166:57)
angular5>           at Observable._trySubscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:172:25)
angular5>           at Observable.subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:160:93)
angular5>           at Object.subscribeToResult (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\util\subscribeToResult.js:23:27)
angular5>           at MergeMapSubscriber._innerSub (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:132:38)
angular5>           at MergeMapSubscriber._tryNext (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:129:14)
angular5>           at MergeMapSubscriber._next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:112:18)
angular5>           at MergeMapSubscriber.Subscriber.next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Subscriber.js:93:18)
angular5>           at ScalarObservable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\observable\ScalarObservable.js:49:24)
angular5>           at resolvePromise (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:814:31)
angular5>           at resolvePromise (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:771:17)
angular5>           at E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:873:17
angular5>           at ZoneDelegate.invokeTask (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:421:31)
angular5>           at Object.onInvokeTask (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\core\bundles\core.umd.js:4789:33)
angular5>           at ZoneDelegate.invokeTask (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:420:36)
angular5>           at Zone.runTask (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:188:47)
angular5>           at drainMicroTaskQueue (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:595:35)
angular5>           at ZoneTask.invokeTask (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:500:21)
angular5>           at ZoneTask.invoke (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\zone.js\dist\zone-node.js:485:48)
angular5>         rejection: ReferenceError: XMLHttpRequest is not defined
angular5>           at BrowserXhr.build (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2125:19)
angular5>           at Observable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2166:57)
angular5>           at Observable._trySubscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:172:25)
angular5>           at Observable.subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:160:93)
angular5>           at Object.subscribeToResult (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\util\subscribeToResult.js:23:27)
angular5>           at MergeMapSubscriber._innerSub (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:132:38)
angular5>           at MergeMapSubscriber._tryNext (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:129:14)
angular5>           at MergeMapSubscriber._next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:112:18)
angular5>           at MergeMapSubscriber.Subscriber.next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Subscriber.js:93:18)
angular5>           at ScalarObservable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\observable\ScalarObservable.js:49:24),
angular5>         promise: 
angular5>          ZoneAwarePromise {
angular5>            __zone_symbol__state: 0,
angular5>            __zone_symbol__value: ReferenceError: XMLHttpRequest is not defined
angular5>           at BrowserXhr.build (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2125:19)
angular5>           at Observable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2166:57)
angular5>           at Observable._trySubscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:172:25)
angular5>           at Observable.subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:160:93)
angular5>           at Object.subscribeToResult (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\util\subscribeToResult.js:23:27)
angular5>           at MergeMapSubscriber._innerSub (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:132:38)
angular5>           at MergeMapSubscriber._tryNext (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:129:14)
angular5>           at MergeMapSubscriber._next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:112:18)
angular5>           at MergeMapSubscriber.Subscriber.next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Subscriber.js:93:18)
angular5>           at ScalarObservable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\observable\ScalarObservable.js:49:24) },
angular5>         zone: 
angular5>          Zone {
angular5>            _properties: { isAngularZone: true },
angular5>            _parent: 
angular5>             Zone {
angular5>               _properties: {},
angular5>               _parent: null,
angular5>               _name: '<root>',
angular5>               _zoneDelegate: [Object] },
angular5>            _name: 'angular',
angular5>            _zoneDelegate: 
angular5>             ZoneDelegate {
angular5>               _taskCounts: [Object],
angular5>               zone: [Circular],
angular5>               _parentDelegate: [Object],
angular5>               _forkZS: null,
angular5>               _forkDlgt: null,
angular5>               _forkCurrZone: [Object],
angular5>               _interceptZS: null,
angular5>               _interceptDlgt: null,
angular5>               _interceptCurrZone: [Object],
angular5>               _invokeZS: [Object],
angular5>               _invokeDlgt: [Object],
angular5>               _invokeCurrZone: [Circular],
angular5>               _handleErrorZS: [Object],
angular5>               _handleErrorDlgt: [Object],
angular5>               _handleErrorCurrZone: [Circular],
angular5>               _scheduleTaskZS: [Object],
angular5>               _scheduleTaskDlgt: [Object],
angular5>               _scheduleTaskCurrZone: [Circular],
angular5>               _invokeTaskZS: [Object],
angular5>               _invokeTaskDlgt: [Object],
angular5>               _invokeTaskCurrZone: [Circular],
angular5>               _cancelTaskZS: [Object],
angular5>               _cancelTaskDlgt: [Object],
angular5>               _cancelTaskCurrZone: [Circular],
angular5>               _hasTaskZS: [Object],
angular5>               _hasTaskDlgt: [Object],
angular5>               _hasTaskDlgtOwner: [Circular],
angular5>               _hasTaskCurrZone: [Circular] } },
angular5>         task: 
angular5>          ZoneTask {
angular5>            _zone: 
angular5>             Zone {
angular5>               _properties: [Object],
angular5>               _parent: [Object],
angular5>               _name: 'angular',
angular5>               _zoneDelegate: [Object] },
angular5>            runCount: 0,
angular5>            _zoneDelegates: null,
angular5>            _state: 'notScheduled',
angular5>            type: 'microTask',
angular5>            source: 'Promise.then',
angular5>            data: 
angular5>             ZoneAwarePromise {
angular5>               __zone_symbol__state: 0,
angular5>               __zone_symbol__value: ReferenceError: XMLHttpRequest is not defined
angular5>           at BrowserXhr.build (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2125:19)
angular5>           at Observable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\@angular\common\bundles\common-http.umd.js:2166:57)
angular5>           at Observable._trySubscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:172:25)
angular5>           at Observable.subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Observable.js:160:93)
angular5>           at Object.subscribeToResult (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\util\subscribeToResult.js:23:27)
angular5>           at MergeMapSubscriber._innerSub (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:132:38)
angular5>           at MergeMapSubscriber._tryNext (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:129:14)
angular5>           at MergeMapSubscriber._next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\operators\mergeMap.js:112:18)
angular5>           at MergeMapSubscriber.Subscriber.next (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\Subscriber.js:93:18)
angular5>           at ScalarObservable._subscribe (E:\TEST\Angular-5-CSharp\ClientApp\node_modules\rxjs\observable\ScalarObservable.js:49:24) },
angular5>            scheduleFn: undefined,
angular5>            cancelFn: null,
angular5>            callback: [Function],
angular5>            invoke: [Function] } }
```

**Comment by vasyliv** [comment]
solved by removing the HttpClientModule from lazy module
