### ISSUE TITLE
Flaky tests: WebApiTemplate_Works_NetCore et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#620]
This test [fails](http://aspnetci/viewLog.html?buildId=507950&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : Process exited with code -2147352562
StdErr: No templates matched the input template name: webapi.
StdOut: Usage: new [options]
Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
Templates                                 Short Name       Language          Tags          
-------------------------------------------------------------------------------------------
Console Application                       console          [C#], F#, VB      Common/Console
Class library                             classlib         [C#], F#, VB      Common/Library
Unit Test Project                         mstest           [C#], F#, VB      Test/MSTest   
xUnit Test Project                        xunit            [C#], F#, VB      Test/xUnit    
Razor Page                                page             [C#]              Web/ASP.NET   
MVC ViewImports                           viewimports      [C#]              Web/ASP.NET   
MVC ViewStart                             viewstart        [C#]              Web/ASP.NET   
ASP.NET Core with Angular                 angular          [C#]              Web/MVC/SPA   
ASP.NET Core with React.js                react            [C#]              Web/MVC/SPA   
ASP.NET Core with React.js and Redux      reactredux       [C#]              Web/MVC/SPA   
global.json file                          globaljson                         Config        
NuGet Config                              nugetconfig                        Config        
Web Config                                webconfig                          Config        
Solution File                             sln                                Solution      
TypeScript file                           tsfile                             Web/Script    
LESS Style Sheet                          less                               Web/Style     
SCSS Style Sheet (SASS)                   scss                               Web/Style     
Examples:
    dotnet new console 
    dotnet new webconfig
    dotnet new --help
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.TemplateTestBase.RunDotNetNew(String templateName, String targetFrameworkOverride, String auth, String language, Boolean useLocalDB, Boolean noHttps) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 57
   at Templates.Test.WebApiTemplateTest.WebApiTemplateImpl(String targetFrameworkOverride) in /_/test/Templates.Test/WebApiTemplateTest.cs:line 30
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new webapi --debug:custom-hive "C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\.templateengine" [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.a15d00d4e60046b48b6e804565a7924e]
Usage: new [options]
Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
[ERROR] No templates matched the input template name: webapi.
[ERROR] 
Templates                                 Short Name       Language          Tags          
-------------------------------------------------------------------------------------------
Console Application                       console          [C#], F#, VB      Common/Console
Class library                             classlib         [C#], F#, VB      Common/Library
Unit Test Project                         mstest           [C#], F#, VB      Test/MSTest   
xUnit Test Project                        xunit            [C#], F#, VB      Test/xUnit    
Razor Page                                page             [C#]              Web/ASP.NET   
MVC ViewImports                           viewimports      [C#]              Web/ASP.NET   
MVC ViewStart                             viewstart        [C#]              Web/ASP.NET   
ASP.NET Core with Angular                 angular          [C#]              Web/MVC/SPA   
ASP.NET Core with React.js                react            [C#]              Web/MVC/SPA   
ASP.NET Core with React.js and Redux      reactredux       [C#]              Web/MVC/SPA   
global.json file                          globaljson                         Config        
NuGet Config          
...
```

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=513991&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=514334&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=514430&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515134&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=514929&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515383&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515336&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515544&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515782&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515977&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515992&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515925&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516180&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516660&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516645&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516549&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516714&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516700&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516834&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516957&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516943&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517017&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517196&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517757&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=517599&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518436&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518510&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518585&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518699&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519450&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519339&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519558&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519492&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519586&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519572&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519624&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519689&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=520895&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=522188&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=523211&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=524711&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
WebApiTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=524676&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
This was fixed by my recent blast of fixes to Templating.
