### ISSUE TITLE
Flaky tests: EmptyWebTemplate_Works_NetFramework et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#622]
This test [fails](http://aspnetci/viewLog.html?buildId=507950&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : Process exited with code -2147352571
StdErr: Invalid input switch:
  --target-framework-override
  net461
StdOut: Usage: new [options]
Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
Web Config
Author: Microsoft
Description: A file used to configure Web Application settings
    (No Parameters)
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.TemplateTestBase.RunDotNetNew(String templateName, String targetFrameworkOverride, String auth, String language, Boolean useLocalDB, Boolean noHttps) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 57
   at Templates.Test.EmptyWebTemplateTest.EmptyWebTemplateImpl(String targetFrameworkOverride) in /_/test/Templates.Test/EmptyWebTemplateTest.cs:line 30
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new web --debug:custom-hive "C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\.templateengine" --target-framework-override net461 [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.fee317422c274580a58f7a46bb17b1bb]
Usage: new [options]
Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
[ERROR] Invalid input switch:
[ERROR]   --target-framework-override
[ERROR]   net461
Web Config
Author: Microsoft
Description: A file used to configure Web Application settings
    (No Parameters)
```

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=514334&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=514430&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515134&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=514929&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515383&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515336&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=515925&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516180&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516645&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516549&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516714&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516834&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=516943&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=517599&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=519339&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=519492&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed again](http://aspnetci/viewLog.html?buildId=519572&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=520895&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=522188&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=523413&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=524711&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetFramework [failed with about the same error](http://aspnetci/viewLog.html?buildId=524676&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
This was fixed by my recent blast of fixes to Templating.
