### ISSUE TITLE
Flaky test: EmptyWebTemplate_Works_NetCore

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#623]
This test [fails](http://aspnetci/viewLog.html?buildId=507950&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : Process exited with code 1
StdErr: 
StdOut: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.Helpers.AspNetProcess..ctor(ITestOutputHelper output, String workingDirectory, String projectName, String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/AspNetProcess.cs:line 66
   at Templates.Test.TemplateTestBase.StartAspNetProcess(String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 205
   at Templates.Test.EmptyWebTemplateTest.EmptyWebTemplateImpl(String targetFrameworkOverride) in /_/test/Templates.Test/EmptyWebTemplateTest.cs:line 30
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new web --debug:custom-hive "C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\.templateengine" [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.018bec58b67d44b9b3da7d245add9cc8]
The template "Web Config" was created successfully.
Building ASP.NET application...
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe build --no-restore -c Debug [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.018bec58b67d44b9b3da7d245add9cc8]
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=514334&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=514430&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515134&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=514929&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515383&buildTypeId=Lite_UniverseTest).

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515336&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515544&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515782&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515977&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=515925&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516660&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516645&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516549&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516714&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516700&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516834&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516957&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=516943&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517017&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517196&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=517599&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518436&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518510&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518585&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518699&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519073&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519450&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519339&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519558&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519492&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519586&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519572&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519624&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed again](http://aspnetci/viewLog.html?buildId=519689&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=520895&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=522188&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=523211&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
He's another flaky templating test that I haven't root caused yet.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=524711&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
EmptyWebTemplate_Works_NetCore [failed with about the same error](http://aspnetci/viewLog.html?buildId=524676&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ajaybhargavb** [comment]
Fixed by @ryanbrandenburg with d95f9716932cae55933c0a4700fec3513c55c92f
