### ISSUE TITLE
Test failure: MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#673]
This test [fails](http://aspnetci/viewLog.html?buildId=528510&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Exception : Process exited with code 1
StdErr: 
StdOut: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\u001d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\u001d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\u001d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
Build FAILED.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\u001d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\u001d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\u001d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:03.01
   at Templates.Test.Helpers.ProcessEx.WaitForExit(Boolean assertSuccess) in /_/test/Templates.Test/Helpers/ProcessEx.cs:line 150
   at Templates.Test.Helpers.AspNetProcess..ctor(ITestOutputHelper output, String workingDirectory, String projectName, String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/AspNetProcess.cs:line 70
   at Templates.Test.TemplateTestBase.StartAspNetProcess(String targetFrameworkOverride, Boolean publish) in /_/test/Templates.Test/Helpers/TemplateTestBase.cs:line 212
   at Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthImpl(String targetFrameworkOverride, String languageOverride, Boolean noHttps) in /_/test/Templates.Test/MvcTemplateTest.cs:line 73
------- Stdout: -------
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe new mvc --debug:custom-hive "C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\.templateengine" -lang F# [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04]
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.
Processing post-creation actions...
Running 'dotnet restore' on C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj...
  Restoring packages for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj...
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\obj\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.nuget.g.props.
  Generating MSBuild file C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\obj\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.nuget.g.targets.
  Restore completed in 1 sec for C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj.
Restore succeeded.
Building ASP.NET application...
==> C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\dotnet.exe build --no-restore -c Debug [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04]
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\x1d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\x1d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\x1d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\AspNet.Template.c309de36e074442aaf98681b1bc5bf04.fsproj]
Build FAILED.
FSC : error FS0078: Unable to find the file 'C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\Windows.winmd' in any of\x1d C:\b\w\33bdfc1cae7b2a38\packages\microsoft.netcore.app\3.0.0-preview1-26810-02\ref\netcoreapp3.0\x1d C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04\x1d C:\b\w\33bdfc1cae7b2a38\.dotnet\x64\sdk\2.1.302\FSharp\ [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp3.0\TestTemplates\AspNet.Template.c309de36e074442aaf98681b1bc5bf04
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=529004&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=529533&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
This appears to be a bug in the sdk. It as best as I can tell this would happen on any netcoreapp3.0 fsharp project. I filed dotnet/cli#9828 against them regarding this.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=530209&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=531083&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
Reduced the priority as we're just tracking this bug.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=532022&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=533306&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
I talked it over with @natemcmaster, we don't have a 3.0 SDK to work with yet, so we're going to skip the test for now and circle back in 3.0.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=534200&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=535151&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=535305&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
We skipped this in aspnet/Templating#678. This issue now tracks reverting that commit once we take a 3.0 SDK.

**Comment by aspnet-hello** [comment]
MvcTemplate_NoAuth_Works_NetCore_ForFSharpTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=535585&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=581392&buildTypeId=Lite_UniverseTest) on master at 3:43:02 AM:
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- AngularTemplate_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- ReactReduxTemplate_Works_NetCore
- WebApiTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=581689&buildTypeId=Lite_UniverseTest) on master at 3:22:09 AM:
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- AngularTemplate_Works_NetCore
- WebApiTemplate_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- MvcTemplate_IndividualAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=582246&buildTypeId=Lite_UniverseTest) on master at 3:41:00 PM:
- ReactTemplate_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- WebApiTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- AngularTemplate_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=582667&buildTypeId=Lite_UniverseTest) on master at 3:33:20 PM:
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- WebApiTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- ReactTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- AngularTemplate_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=583243&buildTypeId=Lite_UniverseTest) on master at 5:10:31 PM:
- RazorPagesTemplate_NoAuth_Works_NetCore
- WebApiTemplate_Works_NetCore
- ReactTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- AngularTemplate_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- (And 1 more test failures in this build)

**Comment by ryanbrandenburg** [comment]
As per [this comment](https://github.com/aspnet/BuildTools/pull/824) we are still blocked on taking a 3.0 SDK.

**Comment by ryanbrandenburg** [comment]
There will be another attempt to take 3.0 SDK once [this issue](https://github.com/dotnet/sdk/issues/2620) is resolved.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=583626&buildTypeId=Lite_UniverseTest) on master at 3:42:40 PM:
- WebApiTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- ReactReduxTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- AngularTemplate_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=584673&buildTypeId=Lite_UniverseTest) on master at 3:10:00 PM:
- RazorPagesTemplate_NoAuth_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- WebApiTemplate_Works_NetCore
- AngularTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- ReactTemplate_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585124&buildTypeId=Lite_UniverseTest) on master at 3:24:08 AM:
- RazorPagesTemplate_NoAuth_Works_NetCore
- ReactTemplate_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- AngularTemplate_Works_NetCore
- WebApiTemplate_Works_NetCore
- RazorPagesTemplate_IndividualAuth_Works_NetCore
- (And 1 more test failures in this build)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 11 failures [with about the same error](http://aspnetci/viewLog.html?buildId=585327&buildTypeId=Lite_UniverseTest) on master at 3:38:37 PM:
- RazorPagesTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- ReactTemplate_Works_NetCore
- MvcTemplate_IndividualAuth_Works_NetCore
- ReactReduxTemplate_Works_NetCore
- WebApiTemplate_Works_NetCore
- RazorPagesTemplate_NoAuth_Works_NetCore
- MvcTemplate_IndividualAuth_UsingLocalDB_Works_NetCore
- AngularTemplate_Works_NetCore
- EmptyWebTemplate_Works_NetCore
- MvcTemplate_NoAuth_Works_NetCore_ForDefaultTemplate
- (And 1 more test failures in this build)
