### ISSUE TITLE
Test failure: MvcTemplate_NoAuth_NoHttps_Works_NetFramework_ForFSharpTemplate

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Templating#705]
This test [fails](http://aspnetci/viewLog.html?buildId=537530&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
ASP.NET process exited without listening for requests.
Output: info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\asplab\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Application startup exception: Microsoft.AspNetCore.Routing.RouteCreationException: An error occurred while creating the route with name 'default' and pattern '{controller=Home}/{action=Index}/{id?}'. ---> System.InvalidOperationException: The route parameter 'controller' has both an inline default value and an explicit default value specified. A route parameter cannot contain an inline default value when a default value is specified explicitly. Consider removing one of them.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitPart|10_3(RoutePatternPart part, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitSegment|10_2(RoutePatternPathSegment segment, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.PatternCore(String rawText, IDictionary`2 defaults, IDictionary`2 parameterPolicies, IEnumerable`1 segments)
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at AspNet.Template.a572740f7ca34eb39396b6e48a888657.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
Microsoft.AspNetCore.Routing.RouteCreationException: An error occurred while creating the route with name 'default' and pattern '{controller=Home}/{action=Index}/{id?}'. ---> System.InvalidOperationException: The route parameter 'controller' has both an inline default value and an explicit default value specified. A route parameter cannot contain an inline default value when a default value is specified explicitly. Consider removing one of them.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitPart|10_3(RoutePatternPart part, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitSegment|10_2(RoutePatternPathSegment segment, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.PatternCore(String rawText, IDictionary`2 defaults, IDictionary`2 parameterPolicies, IEnumerable`1 segments)
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at AspNet.Template.a572740f7ca34eb39396b6e48a888657.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Error: 
Unhandled Exception: Microsoft.AspNetCore.Routing.RouteCreationException: An error occurred while creating the route with name 'default' and pattern '{controller=Home}/{action=Index}/{id?}'. ---> System.InvalidOperationException: The route parameter 'controller' has both an inline default value and an explicit default value specified. A route parameter cannot contain an inline default value when a default value is specified explicitly. Consider removing one of them.
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitPart|10_3(RoutePatternPart part, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.<PatternCore>g__VisitSegment|10_2(RoutePatternPathSegment segment, <>c__DisplayClass10_0& )
   at Microsoft.AspNetCore.Routing.Patterns.RoutePatternFactory.PatternCore(String rawText, IDictionary`2 defaults, IDictionary`2 parameterPolicies, IEnumerable`1 segments)
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Builder.MvcEndpointInfo..ctor(String name, String pattern, RouteValueDictionary defaults, IDictionary`2 constraints, RouteValueDictionary dataTokens, ParameterPolicyFactory parameterPolicyFactory)
   at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
   at AspNet.Template.a5
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
MvcTemplate_NoAuth_NoHttps_Works_NetFramework_ForDefaultTemplate [failed with about the same error](http://aspnetci/viewLog.html?buildId=537530&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
@JamesNK merged a fix for this into Routing [here](https://github.com/aspnet/Routing/commit/15e46ad323943f9086d9558971cfc7760a92b9df).
